# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c781bfa0b1b80304bb7ba4fc934131c22c069e04d5f07f8936b3692952b6ff1f61747abeeedc6273fdc38ffdfe08feffd1444f78f5438a5d67d81a481c296311

test:
  secret_key_base: c97e5da6330c4a828d6f43f6764e10ae3248b79897cf9945fca49ae79dccaee6fcc0396eb7f34d15b1fe35566797488e9f63116f4a1177b1786893e1449530ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
